### ISSUE TITLE
[Question] Is metadata supported?

### ISSUE THREAD

**Issue by gustawdaniel** [poetapp/frost-client#221] opened 2019-02-04 18:47 UTC
I ask because the data model presented in the readme is constrained.

If I would like to integrate with a more mature blogging platform like Ghost then the following data model is used:

> https://docs.ghost.org/api/content/#posts

So I can't use `meta_title` and `meta_desccription`. Can I extend the model of `work`? If yes how to do it? If no, can we introduce field with a flexible structure like `metadata` with value like serialized JSON or JSON?

Wordpress also has a more rich model of post

> https://developer.wordpress.org/rest-api/reference/posts/

Extending your `work` model allows integrating with other publishing platforms.

**Comment by lautarodragan** [comment] 2019-02-05 01:31
Hi @gustawdaniel. 

Support for custom attributes via custom JSON-LD contexts is definitely a planned feature, but not currently implemented.

**Comment by gustawdaniel** [comment] 2019-02-05 11:23
+ Do you have any draft specification? 
+ I see that it is written in typescript. Can I contribute, help in other way? 

The only place I found, where `json-ld` is mentioned:

> https://github.com/poetapp/node/issues/178

**Comment by lautarodragan** [comment] 2019-02-07 07:44
Of course! Would love your contribution. 

We have an issue with a little bit of discussion around this, but right now Frost API is closed-source, so that much is off grounds unfortunately.

But basically the issue is that JSON-LD won't sign/canonicalize fields that aren't accounted for in the `context`, so we need to place the proper field definitions there.

Right now we're using a default context for everything, among other reasons to keep things running as they were before we migrated to JSON-LD.

From the Frost side of things, the main issue is a UX one: 
- Should we ask users to send the context over and over in every request? Seems like a waste of bandwidth and effort
- Should we try and infer a context out of the posted work?
- Should we provide a UI & API to support uploading and managing custom contexts, giving them ids and having the posted work reference one of those?
- A combination of the above?
- Other ideas we haven't discussed? (Feedback welcome!)

The functionality itself should already be supported by poet-js and the node. There's [unit tests](https://github.com/poetapp/poet-js/blob/master/src/VerifiableClaim.test.ts#L101-L146) in place for it in poet-js, so we should really be mostly fine in that sense.

**Comment by gustawdaniel** [comment] 2019-02-07 11:56
* Should we ask users to send the context over and over in every request? Seems like a waste of bandwidth and effort

> Contexts can either be directly embedded into the document or be referenced.

https://json-ld.org/spec/latest/json-ld/#the-context

Context should be always selected, but probably reference is more efficient. I propose to give choice for a user and think about incentive to use best solution form bandwidth point of view.

* Should we try and infer a context out of the posted work?

This question is probably connected with the value of blockchain space. If you want to save space of data then contexts should be as possible as referenced. In this case, you should have possibly of transform custom context to reference pacing it in public space as URL.

* Should we provide a UI & API to support uploading and managing custom contexts, giving them ids and having the posted work reference one of those?

I propose to find a platform that makes it possible. In docs https://schema.org/docs/schemas.html there is info about `External extensions`, but no official tool proposed. So firstly research, if not exists, then creating API to support uploading and managing custom contexts is a great idea for apart project, because it is probably that if you want this service, other people will need them too.

* A combination of the above?

Maybe start from support only for referenced contexts, then if users will need custom context find/create the platform for uploading/managing contexts. 

https://schema.org/CreativeWork

**Comment by lautarodragan** [comment] 2019-06-05 20:37
It's been a while but thank you @gustawdaniel for your input!

Now this is in the roadmap and we'll be soon working on it.

Since Frost is now open-source, I'll close this a a duplicate of https://github.com/poetapp/frost-api/issues/552 to keep the conversation in one place.

**Closed by lautarodragan** 2019-06-05 20:37 UTC
