### ISSUE TITLE
Wrong structure folders in the build

### ISSUE THREAD

**Issue by wzalazar** [poetapp/frost-client#80] opened 2018-08-22 18:47 UTC
This appears when we have in the `include` option in the `tsconfig.json` the folder `typings`, like this:

```
"include": [
    "./src/**/*",
    "./typings/**/*"
 ],
```

the problem occurs when in the `typings` folder has subdirectories, for example:

```
typings 
  | -> riteway
       |- > index.ts
```

the final output will be:

```
dist 
  | -> /src
  | -> /typings
```

but, if we change the folder typings, without subdirectories

```
typings 
  | -> riteway.d.ts
```

the final output will be:

```
dist
  | -> app.js
```

it's dangerous because it changes the final structure and it has a strong dependency with the `package.json`

for this reason, I recommend:

- No subdirectories in the `typings` folder

**Comment by lautarodragan** [comment] 2018-08-22 19:47
Agreed, typings directory shouldn’t have subdirectories

**Comment by geoffturk** [comment] 2018-08-23 09:41
It looks like we have to change the `riteway` typings location in most of the projects. I'll assign this to you @wzalazar. Thanks.

**Comment by lautarodragan** [comment] 2018-08-24 03:10
For reference: the issue ISN'T the subdirectories, it's that the file isn't named `*.d.ts`, but rather, just `*.ts`.

`.d.ts` files are stripped away from the build completely since they only matter at build time. They contain TypeScript code that has no JavaScript counter part and thus is simply deleted, only used to check if the build is right.

If all files in an included directory are `.d.ts` files, they will all be deleted by `tsc` and thus the entire directory will disappear.

**Closed** 2018-08-24 03:16 UTC
Labels: bug
